import "./globals.css";
import Link from "next/link";
import Script from "next/script";
import Navbar from "../../components/Navbar";

export const metadata = {
  title: "NewsAdda — AI-Powered Automated Blog",
  description:
    "Stay ahead with automated, real-time technology, cricket, fashion, and politics updates generated by advanced Gemini AI, monetized with Google AdSense.",
  keywords:
    "tech news, AI blogger, Gemini AI, Next.js SEO, automated blog, AdSense monetization, cricket, fashion, politics",
  openGraph: {
    title: "NewsAdda — AI-Powered Automated Blog",
    description: "Real-time updates generated by Gemini AI.",
    url: "https://newsadda.com",
    siteName: "NewsAdda",
    images: [
      {
        url: "https://images.unsplash.com/photo-1618401471353-b98aedd07871?q=80&w=1200",
        width: 1200,
        height: 630,
        alt: "NewsAdda Blog Feed",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Google AdSense Auto Ads */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8945078741780854"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />

        <div className="app-container">
          {/* Interactive Header Navigation */}
          <Navbar />

          {/* Core Content Viewport */}
          {children}

          {/* Shared Site Footer */}
          <footer className="footer">
            <div className="footer-content">
              <div className="logo-wrapper" style={{ cursor: "default", opacity: 0.75 }}>
                <div className="logo-icon" style={{ boxShadow: "none" }}>N</div>
                <span className="logo-text" style={{ fontSize: "1.2rem" }}>
                  News<span className="logo-accent">Adda</span>
                </span>
              </div>
              <p style={{ maxWidth: "540px", color: "var(--text-muted)", lineHeight: 1.65 }}>
                NewsAdda is a highly-optimized AI autopilot blog platform utilizing server-rendered
                Next.js for elite Google SEO indexation, powered by Gemini AI.
              </p>
              <div className="footer-links">
                <Link href="/">Home Feed</Link>
                <Link href="/tech-dashboard">Tech Dashboard</Link>
                <a href="https://google.com/adsense" target="_blank" rel="noreferrer">
                  AdSense
                </a>
              </div>
              <p style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>
                © 2026 NewsAdda. All rights reserved. Powered by Google Gemini.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
