import "./globals.css";
import AdSlot from "../../components/AdSlot";
import Link from "next/link";

export const metadata = {
  title: "NewsAdda - AI-Powered Automated Tech Blog",
  description: "Stay ahead with automated, real-time technology, science, and business updates generated by advanced Gemini AI, monetized with Google AdSense.",
  keywords: "tech news, AI blogger, Gemini AI, Next.js SEO, automated blog, AdSense monetization",
  openGraph: {
    title: "NewsAdda - AI-Powered Automated Tech Blog",
    description: "Real-time technology and science updates generated by Gemini AI.",
    url: "https://newsadda.com",
    siteName: "NewsAdda",
    images: [
      {
        url: "https://images.unsplash.com/photo-1618401471353-b98aedd07871?q=80&w=1200",
        width: 1200,
        height: 630,
        alt: "NewsAdda Tech Feed",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="app-container">
          {/* Header Navigation */}
          <header className="navbar">
            <div className="navbar-content">
              <Link href="/" className="logo-wrapper">
                <div className="logo-icon">N</div>
                <span className="logo-text">
                  News<span className="logo-accent">Adda</span>
                </span>
              </Link>
              <nav className="nav-links">
                <Link href="/tech-dashboard" className="nav-link">
                  Tech Dashboard
                </Link>
                <a href="https://newsapi.org" target="_blank" rel="noopener noreferrer" className="nav-link">
                  News API
                </a>
                <a href="https://aistudio.google.com" target="_blank" rel="noopener noreferrer" className="nav-link">
                  Gemini Studio
                </a>
              </nav>
            </div>
          </header>

          {/* Left Sidebar Fixed Ad */}
          <aside className="sidebar-ad-left">
            <AdSlot placement="left" />
          </aside>

          {/* Right Sidebar Fixed Ad */}
          <aside className="sidebar-ad-right">
            <AdSlot placement="right" />
          </aside>

          {/* Core Content Viewport */}
          {children}

          {/* Bottom Sticky Ad Slot */}
          <div className="sticky-bottom-ad-container">
            <AdSlot placement="bottom" />
          </div>

          {/* Shared Site Footer */}
          <footer className="footer">
            <div className="footer-content">
              <div className="logo-wrapper" style={{ cursor: "default", opacity: 0.7 }}>
                <div className="logo-icon" style={{ boxShadow: "none" }}>N</div>
                <span className="logo-text" style={{ fontSize: "1.2rem" }}>News<span className="logo-accent">Adda</span></span>
              </div>
              <p style={{ maxWidth: "600px" }}>
                NewsAdda is a highly-optimized AI autopilot blog platform utilizing server pre-rendered Server Components for elite Google SEO indexation.
              </p>
              <div className="footer-links">
                <Link href="/">Home Feed</Link>
                <Link href="/tech-dashboard">Tech Dashboard</Link>
                <a href="https://google.com/adsense" target="_blank" rel="noreferrer">Google AdSense</a>
              </div>
              <p style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginTop: "12px" }}>
                © 2026 NewsAdda. All rights reserved. Powered by Google Gemini.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
